stages:
  process:
    cmd: python src/process.py -c params.yaml
    deps:
    - data/salaries.csv
    - src/process.py
    params:
    - process.seed
    - process.test_split_size
    outs:
    - outputs/features
  optimize:
    cmd: python src/optimize.py -c params.yaml
    deps:
    - outputs/features
    - src/optimize.py
    params:
    - optimize.n_trials
    - optimize.seed
    outs:
    - outputs/best_params
  train:
    cmd: python src/train.py -c params.yaml
    deps:
    - outputs/features
    - outputs/best_params
    - src/train.py
    outs:
    - outputs/model
  eval:
    cmd: python src/eval.py -c params.yaml
    deps:
    - outputs/features
    - outputs/model/model.pkl
    - src/eval.py
    outs:
    - outputs/eval
metrics:
- outputs/eval/metrics.json
plots:
- outputs/eval/plots/metrics:
    x: step
- outputs/eval/plots/images
