stages:
  process:
    cmd: python src/process.py -c params.yaml
    deps:
    - data/salaries.csv
    - src/process.py
    params:
    - process.seed
    - process.test_split_size
    outs:
    - data/features
  train:
    cmd: python src/train.py -c params.yaml
    deps:
    - data/features
    - src/train.py
    params:
    - train.n_estimators
    - train.seed
    outs:
    - output
